# Generated by Django 4.1.7 on 2023-04-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0013_rename_password_signingup_psswrd_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signingup',
            new_name='signup',
        ),
        migrations.AlterModelTable(
            name='signup',
            table='signup',
        ),
    ]
