# Generated by Django 4.1.7 on 2023-04-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0014_rename_signingup_signup_alter_signup_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='signingup',
        ),
        migrations.AlterModelTable(
            name='signingup',
            table='signingup',
        ),
    ]
