# Generated by Django 4.1.7 on 2023-05-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0015_rename_signup_signingup_alter_signingup_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signingup',
            old_name='uname',
            new_name='username',
        ),
    ]
