# Generated by Django 4.1.7 on 2023-05-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0016_rename_uname_signingup_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signingup',
            old_name='username',
            new_name='uname',
        ),
    ]
